// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Implements;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities
{
    public partial class ChatHistories : AuditedEntity
    {
    
        [Required]
        [StringLength(200)]
        public string FromId { get; set; }
        [Required]
        [StringLength(20)]
        public string ToId { get; set; }
        [Required]
        public string Content { get; set; }
    }
}